### ISSUE TITLE
Feature Request: Add output log to message

### ISSUE THREAD

**Issue by massivetim** [jenkinsci/discord-notifier-plugin#7]
Hi,

is it possible to add a feature to include the output log as attached file to the message in Discord? This would be very helpful for times where you don't have access to your build machine (e.g. you are out of office and your build machine is only accessible within your office network). 

Thanks
Tim

**Comment by KocproZ** [comment]
Hi,
I added the feature, you can test it by downloading hpi file from [here](https://ci.jenkins.io/job/Plugins/job/discord-notifier-plugin/job/master/30/artifact/target/discord-notifier.hpi).
If you decide that it looks good i will release it.

**Comment by melt7777** [comment]
Hello, I have also found this to be a great feature request. So, I tested it and it works as designed.  I believe it will work better with the following modification:

Instead of the attachment called "log" can it be "log.txt", "build.log", the build name + build number.log, or even could it be user specified and revert to a default if not specified?  This would be very helpful, as the file type would be more easily clickable to open in the desired editor/viewer application. 

Thank you so much!

**Comment by massivetim** [comment]
Thank you for the fast response / change. I'll be back in the office next week.

**Comment by KocproZ** [comment]
Now the files are named `buildXX.log`.
[hpi file](https://ci.jenkins.io/job/Plugins/job/discord-notifier-plugin/job/master/32/artifact/target/discord-notifier.hpi)

**Comment by massivetim** [comment]
It's working fine, thank you!

**Comment by surin77** [comment]
Hi, KocproZ! Please tell me how to send build.log through the pipeline?

**Comment by raphaelsamyknewin** [comment]
> o

I wish to know exactly that too
